import "./globals.css";
import Header from "@/components/Header";
import AuthCheck from "@/components/AuthCheck";
export default function RootLayout({children}:{children: React.ReactNode;})
{
    return (
        <html lang="en">
        <head>
            <title>test app</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </head>
        <body>
            <AuthCheck />

            {/*<Header />*/}
            {children}
        </body>
        </html>
    );
}